-- Clean schema rebuild v1 for the crypto payment platform MVP.
-- This file is a replacement-candidate schema, not an incremental migration.
-- It intentionally does not keep the old transactions, ledger_entries, or
-- payout_records tables because their concepts are covered by payments,
-- settlements, and merchant_payouts.

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS `audit_logs`;
DROP TABLE IF EXISTS `settlements`;
DROP TABLE IF EXISTS `crypto_conversions`;
DROP TABLE IF EXISTS `blockchain_transactions`;
DROP TABLE IF EXISTS `payments`;
DROP TABLE IF EXISTS `merchant_payouts`;
DROP TABLE IF EXISTS `kyc_submissions`;
DROP TABLE IF EXISTS `supported_assets`;
DROP TABLE IF EXISTS `admin_users`;
DROP TABLE IF EXISTS `merchants`;

SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE `merchants` (
  `merchant_id` varchar(36) NOT NULL,
  `business_name` varchar(255) NOT NULL,
  `uen` varchar(20) DEFAULT NULL,
  `email` varchar(150) NOT NULL,
  `password_hash` varchar(255) NOT NULL,
  `bank_name` varchar(100) DEFAULT NULL,
  `bank_account_last4` varchar(4) DEFAULT NULL,
  `bank_holder_name` varchar(255) DEFAULT NULL,
  `bank_account_encrypted` text DEFAULT NULL,
  `bank_account_iv` varchar(32) DEFAULT NULL,
  `bank_account_auth_tag` varchar(32) DEFAULT NULL,
  `email_verification_token` varchar(128) DEFAULT NULL,
  `email_verified_at` timestamp NULL DEFAULT NULL,
  `container_id` varchar(64) DEFAULT NULL,
  `wallet_id` varchar(64) DEFAULT NULL,
  `stripe_connected_account_id` varchar(128) DEFAULT NULL,
  `stripe_onboarding_status` varchar(40) NOT NULL DEFAULT 'NOT_STARTED',
  `stripe_details_submitted` tinyint(1) NOT NULL DEFAULT 0,
  `stripe_payouts_enabled` tinyint(1) NOT NULL DEFAULT 0,
  `stripe_charges_enabled` tinyint(1) NOT NULL DEFAULT 0,
  `stripe_requirements_currently_due` json DEFAULT NULL,
  `stripe_requirements_disabled_reason` varchar(255) DEFAULT NULL,
  `stripe_status_synced_at` timestamp NULL DEFAULT NULL,
  `payout_enabled` tinyint(1) NOT NULL DEFAULT 1,
  `onboarded_at` timestamp NULL DEFAULT NULL,
  `kyc_status` enum('PENDING','APPROVED','REJECTED','MANUAL_REVIEW') NOT NULL DEFAULT 'PENDING',
  `status` enum('ACTIVE_UNVERIFIED','ACTIVE_ONBOARDED','SUSPENDED','CLOSED') NOT NULL DEFAULT 'ACTIVE_UNVERIFIED',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`merchant_id`),
  UNIQUE KEY `uq_merchants_email` (`email`),
  UNIQUE KEY `uq_merchants_uen` (`uen`),
  KEY `idx_merchants_status` (`status`),
  KEY `idx_merchants_kyc_status` (`kyc_status`),
  KEY `idx_merchants_email_verification_token` (`email_verification_token`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `admin_users` (
  `admin_user_id` int unsigned NOT NULL AUTO_INCREMENT,
  `email` varchar(150) NOT NULL,
  `password_hash` varchar(255) NOT NULL,
  `full_name` varchar(255) NOT NULL,
  `role` varchar(40) NOT NULL DEFAULT 'SUPER_ADMIN',
  `status` varchar(40) NOT NULL DEFAULT 'ACTIVE',
  `last_login_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`admin_user_id`),
  UNIQUE KEY `uq_admin_users_email` (`email`),
  KEY `idx_admin_users_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `merchant_fee_profiles` (
  `merchant_id` varchar(36) NOT NULL,
  `platform_fee_rate` decimal(8,6) NOT NULL DEFAULT '0.015000',
  `maximum_total_rate` decimal(8,6) NOT NULL DEFAULT '0.030000',
  `settlement_delay_days` int NOT NULL DEFAULT 1,
  `settlement_currency` varchar(3) NOT NULL DEFAULT 'SGD',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`merchant_id`),
  CONSTRAINT `fk_merchant_fee_profiles_merchants` FOREIGN KEY (`merchant_id`) REFERENCES `merchants` (`merchant_id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `kyc_submissions` (
  `kyc_submission_id` varchar(36) NOT NULL,
  `merchant_id` varchar(36) NOT NULL,
  `business_type` enum('SOLE_PROPRIETOR','PARTNERSHIP','PRIVATE_LIMITED','LLP') NOT NULL,
  `industry_sector` varchar(100) NOT NULL,
  `registered_address` text NOT NULL,
  `website_url` varchar(255) DEFAULT NULL,
  `sales_channel` varchar(100) DEFAULT NULL,
  `shareholder_count` int unsigned DEFAULT NULL,
  `has_ubo_above_25` tinyint(1) NOT NULL DEFAULT 0,
  `ubo_full_name` varchar(255) DEFAULT NULL,
  `rep_full_name` varchar(255) NOT NULL,
  `rep_designation` varchar(100) NOT NULL,
  `rep_contact_number` varchar(20) NOT NULL,
  `monthly_volume_tier` enum('BELOW_10K','10K_50K','50K_200K','ABOVE_200K') NOT NULL,
  `source_of_funds` varchar(100) DEFAULT NULL,
  `pep_declaration` tinyint(1) NOT NULL DEFAULT 0,
  `terms_accepted` tinyint(1) NOT NULL DEFAULT 0,
  `info_accurate_declaration` tinyint(1) NOT NULL DEFAULT 0,
  `acra_verified` tinyint(1) NOT NULL DEFAULT 0,
  `acra_verification_ref` varchar(64) DEFAULT NULL,
  `n8n_execution_id` varchar(128) DEFAULT NULL,
  `risk_score` int DEFAULT NULL,
  `risk_tier` enum('LOW','MEDIUM','HIGH') DEFAULT NULL,
  `screening_results` json DEFAULT NULL,
  `status` enum('SUBMITTED','UNDER_REVIEW','APPROVED','REJECTED','MANUAL_REVIEW') NOT NULL DEFAULT 'SUBMITTED',
  `reviewer_notes` text DEFAULT NULL,
  `submitted_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `reviewed_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`kyc_submission_id`),
  KEY `idx_kyc_merchant` (`merchant_id`),
  KEY `idx_kyc_status` (`status`),
  CONSTRAINT `fk_kyc_merchants` FOREIGN KEY (`merchant_id`) REFERENCES `merchants` (`merchant_id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `supported_assets` (
  `supported_asset_id` varchar(36) NOT NULL,
  `crypto_symbol` varchar(32) NOT NULL,
  `network` varchar(64) NOT NULL,
  `asset_type` enum('NATIVE','ERC20') NOT NULL,
  `display_name` varchar(100) NOT NULL,
  `token_symbol` varchar(20) DEFAULT NULL,
  `contract_address` varchar(128) DEFAULT NULL,
  `chain_id` int unsigned DEFAULT NULL,
  `decimals` tinyint unsigned NOT NULL,
  `min_confirmations` int unsigned NOT NULL DEFAULT 1,
  `provider_module` varchar(100) NOT NULL,
  `is_testnet` tinyint(1) NOT NULL DEFAULT 1,
  `is_enabled` tinyint(1) NOT NULL DEFAULT 1,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`supported_asset_id`),
  UNIQUE KEY `uq_supported_assets_crypto_network` (`crypto_symbol`, `network`),
  KEY `idx_supported_assets_enabled` (`is_enabled`),
  KEY `idx_supported_assets_contract` (`network`, `contract_address`),
  CONSTRAINT `chk_supported_assets_testnet_only` CHECK (`is_testnet` = 1)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `merchant_payouts` (
  `payout_id` varchar(36) NOT NULL,
  `merchant_id` varchar(36) NOT NULL,
  `payout_reference` varchar(100) NOT NULL,
  `gross_sgd_amount` decimal(12,2) NOT NULL,
  `payout_fee_sgd` decimal(12,2) NOT NULL DEFAULT '0.00',
  `net_payout_sgd_amount` decimal(12,2) NOT NULL,
  `payout_method` enum('BANK_TRANSFER_SIMULATED') NOT NULL DEFAULT 'BANK_TRANSFER_SIMULATED',
  `bank_name` varchar(100) DEFAULT NULL,
  `bank_account_last4` varchar(4) DEFAULT NULL,
  `provider_name` varchar(100) NOT NULL DEFAULT 'MOCK_MAS_LICENSED_PROVIDER',
  `provider_reference` varchar(128) DEFAULT NULL,
  `stripe_transfer_id` varchar(128) DEFAULT NULL,
  `stripe_payout_id` varchar(128) DEFAULT NULL,
  `idempotency_key` varchar(128) DEFAULT NULL,
  `status` enum('NOT_READY','PENDING_APPROVAL','PROCESSING','TRANSFERRED','PAID_OUT','FAILED','CANCELLED') NOT NULL DEFAULT 'NOT_READY',
  `requested_at` timestamp NULL DEFAULT NULL,
  `processing_started_at` timestamp NULL DEFAULT NULL,
  `paid_out_at` timestamp NULL DEFAULT NULL,
  `failed_at` timestamp NULL DEFAULT NULL,
  `failure_reason` varchar(255) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`payout_id`),
  UNIQUE KEY `uq_merchant_payouts_reference` (`payout_reference`),
  UNIQUE KEY `uq_merchant_payouts_idempotency` (`idempotency_key`),
  KEY `idx_merchant_payouts_merchant_status` (`merchant_id`, `status`),
  KEY `idx_merchant_payouts_created_at` (`created_at`),
  CONSTRAINT `fk_merchant_payouts_merchants` FOREIGN KEY (`merchant_id`) REFERENCES `merchants` (`merchant_id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `chk_merchant_payouts_gross_nonnegative` CHECK (`gross_sgd_amount` >= 0),
  CONSTRAINT `chk_merchant_payouts_fee_nonnegative` CHECK (`payout_fee_sgd` >= 0),
  CONSTRAINT `chk_merchant_payouts_net_nonnegative` CHECK (`net_payout_sgd_amount` >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `payments` (
  `payment_id` varchar(36) NOT NULL,
  `merchant_id` varchar(36) NOT NULL,
  `payment_reference` varchar(64) NOT NULL,
  `merchant_order_reference` varchar(100) DEFAULT NULL,
  `description` varchar(500) DEFAULT NULL,
  `customer_reference` varchar(100) DEFAULT NULL,
  `amount_sgd` decimal(12,2) NOT NULL,
  `supported_asset_id` varchar(36) DEFAULT NULL,
  `crypto_symbol_snapshot` varchar(32) DEFAULT NULL,
  `network_snapshot` varchar(64) DEFAULT NULL,
  `expected_crypto_amount` decimal(36,18) DEFAULT NULL,
  `received_crypto_amount` decimal(36,18) NOT NULL DEFAULT '0.000000000000000000',
  `quoted_rate_sgd_per_crypto` decimal(36,18) DEFAULT NULL,
  `quote_expires_at` timestamp NULL DEFAULT NULL,
  `amount_tolerance_bps` int unsigned NOT NULL DEFAULT 100,
  `receiving_address` varchar(128) DEFAULT NULL,
  `qr_code_data` text,
  `payment_instructions` json DEFAULT NULL,
  `provider_name` varchar(100) NOT NULL DEFAULT 'MOCK_MAS_LICENSED_PROVIDER',
  `provider_reference` varchar(128) DEFAULT NULL,
  `status` enum(
    'CREATED',
    'AWAITING_CRYPTO_SELECTION',
    'QR_GENERATED',
    'AWAITING_PAYMENT',
    'PAYMENT_DETECTED',
    'CONFIRMING',
    'CONFIRMED',
    'CONVERTED_TO_SGD',
    'SETTLED',
    'PAID_OUT',
    'KYC_REQUIRED',
    'INSUFFICIENT_FUNDS',
    'UNDERPAID',
    'WRONG_NETWORK',
    'EXPIRED',
    'FAILED',
    'MANUAL_REVIEW_REQUIRED'
  ) NOT NULL DEFAULT 'CREATED',
  `crypto_selected_at` timestamp NULL DEFAULT NULL,
  `qr_generated_at` timestamp NULL DEFAULT NULL,
  `payment_detected_at` timestamp NULL DEFAULT NULL,
  `confirmed_at` timestamp NULL DEFAULT NULL,
  `converted_at` timestamp NULL DEFAULT NULL,
  `settled_at` timestamp NULL DEFAULT NULL,
  `paid_out_at` timestamp NULL DEFAULT NULL,
  `expires_at` timestamp NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`payment_id`),
  UNIQUE KEY `uq_payments_reference` (`payment_reference`),
  KEY `idx_payments_merchant_order_reference` (`merchant_id`, `merchant_order_reference`),
  KEY `idx_payments_customer_reference` (`customer_reference`),
  KEY `idx_payments_merchant_status` (`merchant_id`, `status`),
  KEY `idx_payments_supported_asset` (`supported_asset_id`),
  KEY `idx_payments_receiving_address` (`receiving_address`),
  KEY `idx_payments_quote_expires_at` (`quote_expires_at`),
  KEY `idx_payments_expires_at` (`expires_at`),
  KEY `idx_payments_created_at` (`created_at`),
  CONSTRAINT `fk_payments_merchants` FOREIGN KEY (`merchant_id`) REFERENCES `merchants` (`merchant_id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_payments_supported_assets` FOREIGN KEY (`supported_asset_id`) REFERENCES `supported_assets` (`supported_asset_id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `chk_payments_amount_sgd_positive` CHECK (`amount_sgd` > 0),
  CONSTRAINT `chk_payments_expected_crypto_positive` CHECK (`expected_crypto_amount` IS NULL OR `expected_crypto_amount` > 0),
  CONSTRAINT `chk_payments_received_crypto_nonnegative` CHECK (`received_crypto_amount` >= 0),
  CONSTRAINT `chk_payments_quoted_rate_positive` CHECK (`quoted_rate_sgd_per_crypto` IS NULL OR `quoted_rate_sgd_per_crypto` > 0),
  CONSTRAINT `chk_payments_amount_tolerance_bps` CHECK (`amount_tolerance_bps` <= 10000)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `blockchain_transactions` (
  `blockchain_transaction_id` varchar(36) NOT NULL,
  `payment_id` varchar(36) NOT NULL,
  `supported_asset_id` varchar(36) NOT NULL,
  `crypto_symbol_snapshot` varchar(32) NOT NULL,
  `network_snapshot` varchar(64) NOT NULL,
  `tx_hash` varchar(128) NOT NULL,
  `event_index` int unsigned NOT NULL DEFAULT 0,
  `from_address` varchar(128) DEFAULT NULL,
  `to_address` varchar(128) NOT NULL,
  `amount_crypto` decimal(36,18) NOT NULL,
  `confirmations` int unsigned NOT NULL DEFAULT 0,
  `required_confirmations` int unsigned NOT NULL DEFAULT 1,
  `block_number` bigint unsigned DEFAULT NULL,
  `status` enum('DETECTED','CONFIRMING','CONFIRMED','FAILED','IGNORED') NOT NULL DEFAULT 'DETECTED',
  `raw_payload` json DEFAULT NULL,
  `detected_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `confirmed_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`blockchain_transaction_id`),
  UNIQUE KEY `uq_blockchain_transactions_asset_tx_event` (`supported_asset_id`, `tx_hash`, `event_index`),
  KEY `idx_blockchain_transactions_payment` (`payment_id`),
  KEY `idx_blockchain_transactions_asset` (`supported_asset_id`),
  KEY `idx_blockchain_transactions_to_address` (`to_address`),
  KEY `idx_blockchain_transactions_status` (`status`),
  KEY `idx_blockchain_transactions_confirmations` (`confirmations`),
  CONSTRAINT `fk_blockchain_transactions_payments` FOREIGN KEY (`payment_id`) REFERENCES `payments` (`payment_id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_blockchain_transactions_supported_assets` FOREIGN KEY (`supported_asset_id`) REFERENCES `supported_assets` (`supported_asset_id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `chk_blockchain_transactions_amount_positive` CHECK (`amount_crypto` > 0),
  CONSTRAINT `chk_blockchain_transactions_confirmations_valid` CHECK (`confirmations` <= 4294967295)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `crypto_conversions` (
  `conversion_id` varchar(36) NOT NULL,
  `payment_id` varchar(36) NOT NULL,
  `merchant_id` varchar(36) NOT NULL,
  `crypto_currency` varchar(32) NOT NULL DEFAULT 'ETH',
  `crypto_amount` decimal(36,18) NOT NULL DEFAULT '0.000000000000000000',
  `fiat_currency` varchar(8) NOT NULL DEFAULT 'SGD',
  `quoted_fiat_amount` decimal(12,2) NOT NULL DEFAULT '0.00',
  `quote_exchange_rate` decimal(36,18) DEFAULT NULL,
  `conversion_exchange_rate` decimal(36,18) DEFAULT NULL,
  `actual_fiat_proceeds` decimal(12,2) DEFAULT NULL,
  `conversion_gain_loss` decimal(12,2) DEFAULT NULL,
  `rate_source` varchar(100) NOT NULL DEFAULT 'Coingecko ETH/SGD',
  `faucet_return_address` varchar(128) DEFAULT NULL,
  `faucet_return_tx_hash` varchar(128) DEFAULT NULL,
  `returned_amount` decimal(36,18) DEFAULT NULL,
  `returned_at` timestamp NULL DEFAULT NULL,
  `status` enum('PENDING','CONVERSION_PROCESSING','RETURN_SUBMITTED','RETURN_CONFIRMED','CONVERTED','FAILED') NOT NULL DEFAULT 'PENDING',
  `converted_at` timestamp NULL DEFAULT NULL,
  `failure_reason` varchar(255) DEFAULT NULL,
  `retry_count` int unsigned NOT NULL DEFAULT 0,
  `last_retry_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`conversion_id`),
  UNIQUE KEY `uq_crypto_conversions_payment` (`payment_id`),
  KEY `idx_crypto_conversions_merchant_status` (`merchant_id`, `status`),
  CONSTRAINT `fk_crypto_conversions_payments` FOREIGN KEY (`payment_id`) REFERENCES `payments` (`payment_id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_crypto_conversions_merchants` FOREIGN KEY (`merchant_id`) REFERENCES `merchants` (`merchant_id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `settlements` (
  `settlement_id` varchar(36) NOT NULL,
  `payment_id` varchar(36) NOT NULL,
  `merchant_id` varchar(36) NOT NULL,
  `payout_id` varchar(36) DEFAULT NULL,
  `gross_sgd_amount` decimal(12,2) NOT NULL,
  `provider_fee_sgd` decimal(12,2) NOT NULL DEFAULT '0.00',
  `platform_fee_sgd` decimal(12,2) NOT NULL DEFAULT '0.00',
  `conversion_cost_sgd` decimal(12,2) NOT NULL DEFAULT '0.00',
  `network_fee_sgd` decimal(12,2) NOT NULL DEFAULT '0.00',
  `buffer_reserved_sgd` decimal(12,2) NOT NULL DEFAULT '0.00',
  `buffer_released_sgd` decimal(12,2) NOT NULL DEFAULT '0.00',
  `net_settlement_sgd_amount` decimal(12,2) NOT NULL,
  `conversion_rate` decimal(36,18) DEFAULT NULL,
  `provider_name` varchar(100) NOT NULL DEFAULT 'MOCK_MAS_LICENSED_PROVIDER',
  `provider_reference` varchar(128) DEFAULT NULL,
  `status` enum('PENDING_CONVERSION','CONVERTED_TO_SGD','ELIGIBLE','PROCESSING','TRANSFERRED','HELD','SETTLED','PAID_OUT','FAILED','MANUAL_REVIEW_REQUIRED') NOT NULL DEFAULT 'PENDING_CONVERSION',
  `converted_at` timestamp NULL DEFAULT NULL,
  `settled_at` timestamp NULL DEFAULT NULL,
  `paid_out_at` timestamp NULL DEFAULT NULL,
  `failed_at` timestamp NULL DEFAULT NULL,
  `failure_reason` varchar(255) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`settlement_id`),
  UNIQUE KEY `uq_settlements_payment` (`payment_id`),
  KEY `idx_settlements_merchant_status` (`merchant_id`, `status`),
  KEY `idx_settlements_payout` (`payout_id`),
  KEY `idx_settlements_created_at` (`created_at`),
  CONSTRAINT `fk_settlements_payments` FOREIGN KEY (`payment_id`) REFERENCES `payments` (`payment_id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_settlements_merchants` FOREIGN KEY (`merchant_id`) REFERENCES `merchants` (`merchant_id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_settlements_merchant_payouts` FOREIGN KEY (`payout_id`) REFERENCES `merchant_payouts` (`payout_id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `chk_settlements_gross_nonnegative` CHECK (`gross_sgd_amount` >= 0),
  CONSTRAINT `chk_settlements_provider_fee_nonnegative` CHECK (`provider_fee_sgd` >= 0),
  CONSTRAINT `chk_settlements_platform_fee_nonnegative` CHECK (`platform_fee_sgd` >= 0),
  CONSTRAINT `chk_settlements_net_nonnegative` CHECK (`net_settlement_sgd_amount` >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `settlement_batches` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `merchant_id` varchar(36) NOT NULL,
  `settlement_date` date NOT NULL,
  `gross_amount_cents` bigint NOT NULL,
  `platform_fee_cents` bigint NOT NULL,
  `conversion_cost_cents` bigint NOT NULL DEFAULT 0,
  `network_fee_cents` bigint NOT NULL DEFAULT 0,
  `buffer_reserved_cents` bigint NOT NULL DEFAULT 0,
  `buffer_released_cents` bigint NOT NULL DEFAULT 0,
  `absorbed_by_chainforge_cents` bigint NOT NULL DEFAULT 0,
  `net_amount_cents` bigint NOT NULL,
  `stripe_transfer_id` varchar(255) DEFAULT NULL,
  `status` varchar(30) NOT NULL DEFAULT 'PENDING',
  `failure_reason` text DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `completed_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_settlement_batches_merchant_date` (`merchant_id`, `settlement_date`),
  KEY `idx_settlement_batches_status` (`status`),
  CONSTRAINT `fk_settlement_batches_merchants` FOREIGN KEY (`merchant_id`) REFERENCES `merchants` (`merchant_id`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `audit_logs` (
  `audit_log_id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `merchant_id` varchar(36) DEFAULT NULL,
  `payment_id` varchar(36) DEFAULT NULL,
  `blockchain_transaction_id` varchar(36) DEFAULT NULL,
  `settlement_id` varchar(36) DEFAULT NULL,
  `payout_id` varchar(36) DEFAULT NULL,
  `actor_type` enum('MERCHANT','CUSTOMER','SYSTEM','PROVIDER','ADMIN') NOT NULL,
  `actor_id` varchar(36) DEFAULT NULL,
  `action` varchar(100) NOT NULL,
  `details` json DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`audit_log_id`),
  KEY `idx_audit_logs_merchant_created` (`merchant_id`, `created_at`),
  KEY `idx_audit_logs_payment_created` (`payment_id`, `created_at`),
  KEY `idx_audit_logs_blockchain_transaction_created` (`blockchain_transaction_id`, `created_at`),
  KEY `idx_audit_logs_settlement_created` (`settlement_id`, `created_at`),
  KEY `idx_audit_logs_payout_created` (`payout_id`, `created_at`),
  KEY `idx_audit_logs_actor` (`actor_type`, `actor_id`),
  KEY `idx_audit_logs_action` (`action`),
  CONSTRAINT `fk_audit_logs_merchants` FOREIGN KEY (`merchant_id`) REFERENCES `merchants` (`merchant_id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_audit_logs_payments` FOREIGN KEY (`payment_id`) REFERENCES `payments` (`payment_id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_audit_logs_blockchain_transactions` FOREIGN KEY (`blockchain_transaction_id`) REFERENCES `blockchain_transactions` (`blockchain_transaction_id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_audit_logs_settlements` FOREIGN KEY (`settlement_id`) REFERENCES `settlements` (`settlement_id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `fk_audit_logs_merchant_payouts` FOREIGN KEY (`payout_id`) REFERENCES `merchant_payouts` (`payout_id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `supported_assets` (
  `supported_asset_id`,
  `crypto_symbol`,
  `network`,
  `asset_type`,
  `display_name`,
  `token_symbol`,
  `contract_address`,
  `chain_id`,
  `decimals`,
  `min_confirmations`,
  `provider_module`
) VALUES
  ('asset-btc-testnet', 'BTC', 'BTC_TESTNET', 'NATIVE', 'Bitcoin Testnet', 'tBTC', NULL, NULL, 8, 2, 'btcTestnetProvider'),
  ('asset-eth-sepolia', 'ETH', 'ETH_SEPOLIA', 'NATIVE', 'Sepolia ETH', 'ETH', NULL, 11155111, 18, 1, 'ethSepoliaProvider'),
  ('asset-stablecoin-sepolia', 'TEST_STABLECOIN', 'STABLECOIN_SEPOLIA', 'ERC20', 'Sepolia Test Stablecoin', 'tUSDC', '0x1c7D4B196Cb0C7B01d743Fbc6116a902379C7238', 11155111, 6, 1, 'stablecoinSepoliaProvider');
